apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: core-gateway
  namespace: core-services
spec:
  rules:
    - host: dev.core.appkiosk.example
  tls:
    - hosts:
        - dev.core.appkiosk.example
      secretName: dev-core-gateway-tls
