apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      app.kubernetes.io/environment: dev
      app.kubernetes.io/owner: platform-core

patches:
  - path: ingress.patch.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: core-gateway
      namespace: core-services
  - path: gateway.patch.yaml
    target:
      group: gateway.networking.k8s.io
      version: v1
      kind: Gateway
      name: core-gateway
      namespace: core-services
  - path: control-plane-config.patch.yaml
    target:
      version: v1
      kind: ConfigMap
      name: core-gateway-control-plane-config
      namespace: core-system
  - path: runtime-config.patch.yaml
    target:
      version: v1
      kind: ConfigMap
      name: core-gateway-runtime-config
      namespace: core-services
  - path: control-plane-route.patch.yaml
    target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: core-gateway-control-plane
      namespace: core-services
  - path: runtime-route.patch.yaml
    target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: core-plugin-runtime
      namespace: core-services
