- op: replace
  path: /data/environment
  value: stage
- op: replace
  path: /data/userTokenIssuer
  value: https://keycloak.stage.core.appkiosk.example/realms/core-users
- op: replace
  path: /data/serviceTokenIssuer
  value: https://keycloak.stage.core.appkiosk.example/realms/core-services
