- op: replace
  path: /spec/listeners/0/hostname
  value: stage.core.appkiosk.example
- op: replace
  path: /spec/listeners/0/tls/certificateRefs/0/name
  value: stage-core-gateway-tls
- op: replace
  path: /spec/listeners/1/hostname
  value: stage.core.appkiosk.example
