- op: replace
  path: /spec/rules/0/host
  value: core.appkiosk.example
- op: replace
  path: /spec/tls/0/hosts/0
  value: core.appkiosk.example
- op: replace
  path: /spec/tls/0/secretName
  value: prod-core-gateway-tls
